# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d60c78ca86477eecb475d359cd02f7dddf0b8270e50d56339d99dc3e8f0642b49a5ba138d07a0b3c50a1e8fb0f94ca3e7c9514d1c30b30a4bb8df22eb7a05ea

test:
  secret_key_base: 671262d07ff9dc106956fa5d683e971da39ff118a2e5550eb0d3d8361a8d5a6a7a9612503b6e0d775679a62645e11e6e9040e6eddf0b9187f6795914a9e583cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
